Repository 24-1-CapstoneDesign/Server, pull requests merged in 2024-05, with the labels that each got.

#7 [FEAT]: 구글 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/example/ai_tutor/AiTutorApplication.java
  src/main/java/com/example/ai_tutor/domain/auth/application/AuthService.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/example/ai_tutor/domain/auth/domain/Token.java
  src/main/java/com/example/ai_tutor/domain/auth/domain/repository/CustomAuthorizationRequestRepository.java
  src/main/java/com/example/ai_tutor/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/AuthRes.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/RefreshTokenReq.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/SignInReq.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/TokenMapping.java
  src/main/java/com/example/ai_tutor/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/example/ai_tutor/domain/auth/presentation/AuthController.java
  src/main/java/com/example/ai_tutor/domain/user/domain/Provider.java
  src/main/java/com/example/ai_tutor/domain/user/domain/Role.java
  src/main/java/com/example/ai_tutor/domain/user/domain/User.java
  src/main/java/com/example/ai_tutor/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/ai_tutor/global/DefaultAssert.java
  src/main/java/com/example/ai_tutor/global/config/security/OAuth2Config.java
  src/main/java/com/example/ai_tutor/global/config/security/SecurityConfig.java
  src/main/java/com/example/ai_tutor/global/config/security/auth/OAuth2UserInfo.java
  src/main/java/com/example/ai_tutor/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/example/ai_tutor/global/config/security/auth/company/Google.java
  src/main/java/com/example/ai_tutor/global/config/security/handler/CustomSimpleUrlAuthenticationFailureHandler.java
  src/main/java/com/example/ai_tutor/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
  src/main/java/com/example/ai_tutor/global/config/security/token/CurrentUser.java
  src/main/java/com/example/ai_tutor/global/config/security/token/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/ai_tutor/global/config/security/token/CustomOncePerRequestFilter.java
  src/main/java/com/example/ai_tutor/global/config/security/token/UserPrincipal.java
  src/main/java/com/example/ai_tutor/global/config/security/util/CustomCookie.java
  src/main/java/com/example/ai_tutor/global/error/DefaultAuthenticationException.java
  src/main/java/com/example/ai_tutor/global/error/DefaultException.java
  src/main/java/com/example/ai_tutor/global/payload/ApiResponse.java
  src/main/java/com/example/ai_tutor/global/payload/ErrorCode.java
  src/main/java/com/example/ai_tutor/global/payload/ErrorResponse.java
  src/main/java/com/example/ai_tutor/global/payload/Message.java
  src/main/resources/swagger/applicaion-springdoc.yml
Labels: feature✨

#8 main, develop merge 및 폴더 생성 기능 구현
  .github/workflows/deploy.yml
  .gitignore
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/example/ai_tutor/AiTutorApplication.java
  src/main/java/com/example/ai_tutor/domain/Folder/application/FolderService.java
  src/main/java/com/example/ai_tutor/domain/Folder/domain/repository/FolderRepository.java
  src/main/java/com/example/ai_tutor/domain/Folder/dto/request/FolderCreateReq.java
  src/main/java/com/example/ai_tutor/domain/Folder/presentation/FolderController.java
  src/main/java/com/example/ai_tutor/domain/auth/application/AuthService.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/example/ai_tutor/domain/auth/domain/Token.java
  src/main/java/com/example/ai_tutor/domain/auth/domain/repository/CustomAuthorizationRequestRepository.java
  src/main/java/com/example/ai_tutor/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/AuthRes.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/RefreshTokenReq.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/SignInReq.java
  src/main/java/com/example/ai_tutor/domain/auth/dto/TokenMapping.java
  src/main/java/com/example/ai_tutor/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/example/ai_tutor/domain/auth/presentation/AuthController.java
  src/main/java/com/example/ai_tutor/domain/note/domain/Note.java
  src/main/java/com/example/ai_tutor/domain/user/domain/Provider.java
  src/main/java/com/example/ai_tutor/domain/user/domain/Role.java
  src/main/java/com/example/ai_tutor/domain/user/domain/User.java
  src/main/java/com/example/ai_tutor/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/ai_tutor/global/DefaultAssert.java
  src/main/java/com/example/ai_tutor/global/config/YamlPropertySourceFactory.java
  src/main/java/com/example/ai_tutor/global/config/security/OAuth2Config.java
  src/main/java/com/example/ai_tutor/global/config/security/SecurityConfig.java
  src/main/java/com/example/ai_tutor/global/config/security/auth/OAuth2UserInfo.java
  src/main/java/com/example/ai_tutor/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/example/ai_tutor/global/config/security/auth/company/Google.java
  src/main/java/com/example/ai_tutor/global/config/security/handler/CustomSimpleUrlAuthenticationFailureHandler.java
  src/main/java/com/example/ai_tutor/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
  src/main/java/com/example/ai_tutor/global/config/security/token/CurrentUser.java
  src/main/java/com/example/ai_tutor/global/config/security/token/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/ai_tutor/global/config/security/token/CustomOncePerRequestFilter.java
  src/main/java/com/example/ai_tutor/global/config/security/token/UserPrincipal.java
  src/main/java/com/example/ai_tutor/global/config/security/util/CustomCookie.java
  src/main/java/com/example/ai_tutor/global/error/DefaultAuthenticationException.java
  src/main/java/com/example/ai_tutor/global/error/DefaultException.java
  src/main/java/com/example/ai_tutor/global/payload/ApiResponse.java
  src/main/java/com/example/ai_tutor/global/payload/ErrorCode.java
  src/main/java/com/example/ai_tutor/global/payload/ErrorResponse.java
  src/main/java/com/example/ai_tutor/global/payload/Message.java
  src/main/java/com/example/ai_tutor/global/payload/ResponseCustom.java
  src/main/resources/application.yml
  src/main/resources/swagger/applicaion-springdoc.yml
Labels: feature✨

#16 [FEAT]: 홈 화면에서 사용자 정보 조회
  src/main/java/com/example/ai_tutor/AiTutorApplication.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/example/ai_tutor/domain/user/application/UserService.java
  src/main/java/com/example/ai_tutor/domain/user/domain/User.java
  src/main/java/com/example/ai_tutor/domain/user/dto/HomeUserRes.java
  src/main/java/com/example/ai_tutor/domain/user/presentation/UserController.java
Labels: feature✨, fix⚒️

#18 [FIX]: 로그인 API 오류 수정
  src/main/java/com/example/ai_tutor/domain/auth/application/AuthService.java
  src/main/java/com/example/ai_tutor/global/config/security/token/UserPrincipal.java
Labels: fix⚒️

#26 [FEAT]: 문제 조회 및 답변 작성, 수정
  src/main/java/com/example/ai_tutor/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/example/ai_tutor/domain/practice/application/PracticeService.java
  src/main/java/com/example/ai_tutor/domain/practice/domain/Practice.java
  src/main/java/com/example/ai_tutor/domain/practice/domain/repository/PracticeRepository.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/AnswerReq.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/PracticeRes.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/PracticeResultsRes.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/UpdateAnswersReq.java
  src/main/java/com/example/ai_tutor/domain/practice/presentation/PracticeController.java
  src/main/java/com/example/ai_tutor/domain/user/application/UserService.java
  src/main/java/com/example/ai_tutor/domain/user/dto/HomeUserRes.java
  src/main/java/com/example/ai_tutor/domain/user/presentation/UserController.java
Labels: feature✨, fix⚒️

#29 merge develop to main
  build.gradle
  src/main/java/com/example/ai_tutor/AiTutorApplication.java
  src/main/java/com/example/ai_tutor/domain/Folder/application/FolderService.java
  src/main/java/com/example/ai_tutor/domain/Folder/domain/Folder.java
  src/main/java/com/example/ai_tutor/domain/Folder/domain/repository/FolderRepository.java
  src/main/java/com/example/ai_tutor/domain/Folder/dto/request/FolderCreateReq.java
  src/main/java/com/example/ai_tutor/domain/Folder/dto/request/FolderUpdateReq.java
  src/main/java/com/example/ai_tutor/domain/Folder/dto/response/FolderListRes.java
  src/main/java/com/example/ai_tutor/domain/Folder/dto/response/FolderNameListRes.java
  src/main/java/com/example/ai_tutor/domain/Folder/presentation/FolderController.java
  src/main/java/com/example/ai_tutor/domain/auth/application/AuthService.java
  src/main/java/com/example/ai_tutor/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/example/ai_tutor/domain/note/application/NoteService.java
  src/main/java/com/example/ai_tutor/domain/note/domain/Note.java
  src/main/java/com/example/ai_tutor/domain/note/domain/NoteStatus.java
  src/main/java/com/example/ai_tutor/domain/note/domain/Repository/NoteRepository.java
  src/main/java/com/example/ai_tutor/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/example/ai_tutor/domain/note/dto/request/NoteCreateReq.java
  src/main/java/com/example/ai_tutor/domain/note/dto/request/NoteDeleteReq.java
  src/main/java/com/example/ai_tutor/domain/note/dto/request/NoteStepUpdateReq.java
  src/main/java/com/example/ai_tutor/domain/note/dto/response/NoteListDetailRes.java
  src/main/java/com/example/ai_tutor/domain/note/dto/response/NoteListRes.java
  src/main/java/com/example/ai_tutor/domain/note/presentation/NoteController.java
  src/main/java/com/example/ai_tutor/domain/practice/application/PracticeService.java
  src/main/java/com/example/ai_tutor/domain/practice/domain/Practice.java
  src/main/java/com/example/ai_tutor/domain/practice/domain/repository/PracticeRepository.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/AnswerReq.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/PracticeRes.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/PracticeResultsRes.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/UpdateAnswersReq.java
  src/main/java/com/example/ai_tutor/domain/practice/presentation/PracticeController.java
  src/main/java/com/example/ai_tutor/domain/user/application/UserService.java
  src/main/java/com/example/ai_tutor/domain/user/domain/User.java
  src/main/java/com/example/ai_tutor/domain/user/dto/HomeUserRes.java
  src/main/java/com/example/ai_tutor/domain/user/presentation/UserController.java
  src/main/java/com/example/ai_tutor/global/DefaultAssert.java
  src/main/java/com/example/ai_tutor/global/config/security/AmazonS3Config.java
  src/main/java/com/example/ai_tutor/global/config/security/token/UserPrincipal.java
  src/main/java/com/example/ai_tutor/global/payload/ResponseCustom.java
Labels: feature✨

#32 [FIX]: note repository 중복 오류 수정
  src/main/java/com/example/ai_tutor/domain/note/application/NoteService.java
  src/main/java/com/example/ai_tutor/domain/note/domain/repository/NoteRepository.java
Labels: fix⚒️

#34 [FEAT]: tutor 답변 조회
  .gitignore
  src/main/java/com/example/ai_tutor/domain/note/domain/Note.java
  src/main/java/com/example/ai_tutor/domain/practice/application/PracticeService.java
  src/main/java/com/example/ai_tutor/domain/practice/domain/Practice.java
  src/main/java/com/example/ai_tutor/domain/practice/domain/repository/PracticeRepository.java
  src/main/java/com/example/ai_tutor/domain/practice/dto/PracticeResultsRes.java
  src/main/java/com/example/ai_tutor/domain/practice/presentation/PracticeController.java
Labels: feature✨

#37 [FEAT]: 요약문 수정
  src/main/java/com/example/ai_tutor/domain/note/application/NoteService.java
  src/main/java/com/example/ai_tutor/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/example/ai_tutor/domain/note/dto/response/StepOneRes.java
  src/main/java/com/example/ai_tutor/domain/summary/application/SummaryService.java
  src/main/java/com/example/ai_tutor/domain/summary/domain/Summary.java
  src/main/java/com/example/ai_tutor/domain/summary/dto/request/SummaryUpdateReq.java
  src/main/java/com/example/ai_tutor/domain/summary/presentation/SummaryController.java
Labels: feature✨
